create database if not exists starwars;
use starwars;

create table transport(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	consumables VARCHAR(255),
	denomination VARCHAR(255) UNIQUE NOT NULL,
	cargo_capacity BIGINT,
	passengers INT,
	max_atmosphering_speed INT,
	crew INT,
	lengthiness INT,
	model VARCHAR(255) UNIQUE NOT NULL,
	cost_in_credits BIGINT,
	manufacturer VARCHAR(255),
	image VARCHAR(255) UNIQUE NOT NULL
)
ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (1,'1 year','CR90 corvette',3000000,600,950,165,150,'CR90 corvette',3500000,'Corellian Engineering Corporation','cr90_corvette.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (2,'2 years','Star Destroyer',36000000,NULL,975,47,2,'Imperial I-class Star Destroyer',150000000,'Kuat Drive Yards','star_destroyer.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (3,'2 months','Sand Crawler',50000,30,30,46,13363,'Digger Crawler',150000,'Corellia Mining Corporation','sand_crawler.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (4,'1 month','Sentinel-class landing craft',180000,75,1000,5,38,'Sentinel-class landing craft',240000,'Sienar Fleet Systems, Cyngus Spaceworks','sentinel-class_landing_craft.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (5,'0','T-16 skyhopper',50,1,1200,1,43377,'T-16 skyhopper',14500,'Incom Corporation','t-16_skyhopper.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (6,NULL,'X-34 landspeeder',5,1,250,1,43163,'X-34 landspeeder',10550,'SoroSuub Corporation','x-34_landspeeder.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (7,'2 days','TIE/LN starfighter',65,0,1200,1,43255,'Twin Ion Engine/Ln Starfighter',NULL,'Sienar Fleet Systems','tie/ln_starfighter.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (8,'3 years','Death Star',1000000000000,843,NULL,343,120000,'DS-1 Orbital Battle Station',1000000000000,'Imperial Department of Military Research, Sienar Fleet Systems','death_star.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (9,'2 months','Millennium Falcon',100000,6,1050,4,34.37,'YT-1300 light freighter',100000,'Corellian Engineering Corporation','millennium_falcon.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (10,'1 week','Y-wing',110,0,1000,2,14,'BTL Y-wing',134999,'Koensayr Manufacturing','y-wing.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (11,'1 week','X-wing',110,0,1050,1,43439,'T-65 X-wing',149999,'Incom Corporation','x-wing.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (12,'5 days','TIE Advanced x1',150,0,1200,1,43345,'Twin Ion Engine Advanced x1',NULL,'Sienar Fleet Systems','tie_advanced_x1.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (13,NULL,'Snowspeeder',10,0,650,2,43195,'t-47 airspeeder',NULL,'Incom corporation','snowspeeder.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (14,'6 years','Executor',250000000,38,NULL,279,19,'Executor-class star dreadnought',1143350000,'Kuat Drive Yards, Fondor Shipyards','executor.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (15,'2 days','TIE bomber',NULL,0,850,1,43289,'TIE/sa bomber',NULL,'Sienar Fleet Systems','tie_bomber.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (16,'6 months','Rebel transport',19000000,90,650,6,90,'GR-75 medium transport',NULL,'Gallofree Yards, Inc.','rebel_transport.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (17,NULL,'AT-AT',1000,40,60,5,20,'All Terrain Armored Transport',NULL,'Kuat Drive Yards, Imperial Department of Military Research','at-at.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (18,NULL,'AT-ST',200,0,90,2,2,'All Terrain Scout Transport',NULL,'Kuat Drive Yards, Imperial Department of Military Research','at-st.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (19,'1 day','Storm IV Twin-Pod cloud car',10,0,1500,2,7,'Storm IV Twin-Pod',75000,'Bespin Motors','storm_iv_twin-pod_cloud_car.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (20,'1 month','Slave 1',70000,6,1000,1,43241,'Firespray-31-class patrol and attack',NULL,'Kuat Systems Engineering','slave_1.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (21,'2 months','Imperial shuttle',80000,20,850,6,20,'Lambda-class T-4a shuttle',240000,'Sienar Fleet Systems','imperial_shuttle.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (22,'2 years','EF76 Nebulon-B escort frigate',6000000,75,800,854,300,'EF76 Nebulon-B escort frigate',8500000,'Kuat Drive Yards','ef76_nebulon-b_escort_frigate.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (23,'Live food tanks','Sail barge',2000000,500,100,26,30,'Modified Luxury Sail Barge',285000,'Ubrikkian Industries Custom Vehicle Division','sail_barge.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (24,'1 day','Bantha-II cargo skiff',135000,16,250,5,43348,'Bantha-II',8000,'Ubrikkian Industries','bantha-ii_cargo_skiff.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (25,'2 days','TIE/IN interceptor',75,0,1250,1,43349,'Twin Ion Engine Interceptor',NULL,'Sienar Fleet Systems','tie/in_interceptor.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (26,'2 years','Calamari Cruiser',NULL,1200,NULL,5400,1200,'MC80 Liberty type Star Cruiser',104000000,'Mon Calamari shipyards','calamari_cruiser.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (27,'1 week','A-wing',40,0,1300,1,43349,'RZ-1 A-wing Interceptor',175000,'Alliance Underground Engineering, Incom Corporation','a-wing.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (28,'1 week','B-wing',45,0,950,1,43359,'A/SF-01 B-wing starfighter',220000,'Slayn & Korpil','b-wing.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (29,'1 day','Imperial Speeder Bike',4,1,360,1,3,'74-Z speeder bike',8000,'Aratech Repulsor Company','imperial_speeder_bike.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (30,NULL,'Republic Cruiser',NULL,16,900,9,115,'Consular-class cruiser',NULL,'Corellian Engineering Corporation','republic_cruiser.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (31,'500 days','Droid control ship',4000000000,139000,NULL,175,3170,'Lucrehulk-class Droid Control Ship',NULL,'Hoersch-Kessel Drive, Inc.','droid_control_ship.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (32,NULL,'Vulture Droid',0,0,1200,0,43164,'Vulture-class droid starfighter',NULL,'Haor Chall Engineering, Baktoid Armor Workshop','vulture_droid.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (33,NULL,'Multi-Troop Transport',12000,112,35,4,31,'Multi-Troop Transport',138000,'Baktoid Armor Workshop','multi-troop_transport.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (34,NULL,'Armored Assault Tank',NULL,6,55,4,9.75,'Armoured Assault Tank',NULL,'Baktoid Armor Workshop','armored_assault_tank.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (35,NULL,'Single Trooper Aerial Platform',NULL,0,400,1,2,'Single Trooper Aerial Platform',2500,'Baktoid Armor Workshop','single_trooper_aerial_platform.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (36,'1 day','C-9979 landing craft',1800000,284,587,140,210,'C-9979 landing craft',200000,'Haor Chall Engineering','c-9979_landing_craft.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (37,NULL,'Tribubble bongo',1600,2,85,1,15,'Tribubble bongo',NULL,'Otoh Gunga Bongameken Cooperative','tribubble_bongo.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (38,'7 days','Naboo fighter',65,0,1100,1,11,'N-1 starfighter',200000,'Theed Palace Space Vessel Engineering Corps','naboo_fighter.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (39,NULL,'Naboo Royal Starship',NULL,NULL,920,8,76,'J-type 327 Nubian royal starship',NULL,'Theed Palace Space Vessel Engineering Corps, Nubia Star Drives','naboo_royal_starship.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (40,'30 days','Scimitar',2500000,6,1180,1,43246,'Star Courier',55000000,'Republic Sienar Systems','scimitar.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (41,NULL,'Sith speeder',2,0,180,1,43105,'FC-20 speeder bike',4000,'Razalon','sith_speeder.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (42,'1 year','J-type diplomatic barge',NULL,10,2000,5,39,'J-type diplomatic barge',2000000,'Theed Palace Space Vessel Engineering Corps, Nubia Star Drives','j-type_diplomatic_barge.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (43,NULL,'Zephyr-G swoop bike',200,1,350,1,3.68,'Zephyr-G swoop bike',5750,'Mobquet Swoops and Speeders','zephyr-g_swoop_bike.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (44,NULL,'Koro-2 Exodrive airspeeder',80,1,800,1,43257,'Koro-2 Exodrive airspeeder',NULL,'Desler Gizh Outworld Mobility Corporation','koro-2_exodrive_airspeeder.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (45,NULL,'XJ-6 airspeeder',NULL,1,720,1,43274,'XJ-6 airspeeder',NULL,'Narglatch AirTech prefabricated kit','xj-6_airspeeder.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (46,NULL,'AA-9 Coruscant freighter',NULL,30000,NULL,NULL,390,'Botajef AA-9 Freighter-Liner',NULL,'Botajef Shipyards','aa-9_coruscant_freighter.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (47,'7 days','Jedi starfighter',60,0,1150,1,8,'Delta-7 Aethersprite-class interceptor',180000,'Kuat Systems Engineering','jedi_starfighter.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (48,NULL,'H-type Nubian yacht',NULL,NULL,8000,4,17411,'H-type Nubian yacht',NULL,'Theed Palace Space Vessel Engineering Corps','h-type_nubian_yacht.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (49,NULL,'LAAT/i',170,30,620,6,43207,'Low Altitude Assault Transport/infrantry',NULL,'Rothana Heavy Engineering','laat/i.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (50,NULL,'LAAT/c',40000,0,620,1,28.82,'Low Altitude Assault Transport/carrier',NULL,'Rothana Heavy Engineering','laat/c.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (51,'2 years','Republic Assault ship',11250000,16000,NULL,700,752,'Acclamator I-class assault ship',NULL,'Rothana Heavy Engineering','republic_assault_ship.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (52,'21 days','AT-TE',10000,36,60,6,43144,'All Terrain Tactical Enforcer',NULL,'Rothana Heavy Engineering, Kuat Drive Yards','at-te.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (53,'7 days','SPHA',500,30,35,25,140,'Self-Propelled Heavy Artillery',NULL,'Rothana Heavy Engineering','spha.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (54,NULL,'Flitknot speeder',NULL,0,634,1,2,'Flitknot speeder',8000,'Huppla Pasa Tisc Shipwrights Collective','flitknot_speeder.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (55,'7 days','Neimoidian shuttle',1000,6,880,2,20,'Sheathipede-class transport shuttle',NULL,'Haor Chall Engineering','neimoidian_shuttle.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (56,NULL,'Geonosian starfighter',NULL,0,20000,1,43351,'Nantex-class territorial defense',NULL,'Huppla Pasa Tisc Shipwrights Collective','geonosian_starfighter.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (57,'7 days','Solar Sailer',240,11,1600,3,43146,'Punworcca 116-class interstellar sloop',35700,'Huppla Pasa Tisc Shipwrights Collective','solar_sailer.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (58,'4 years','Trade Federation cruiser',50000000,48247,1050,600,1088,'Providence-class carrier/destroyer',125000000,'Rendili StarDrive, Free Dac Volunteers Engineering corps.','trade_federation_cruiser.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (59,NULL,'Tsmeu-6 personal wheel bike',10,1,330,1,43164,'Tsmeu-6 personal wheel bike',15000,'Z-Gomot Ternbuell Guppat Corporation','tsmeu-6_personal_wheel_bike.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (60,'56 days','Theta-class T-2c shuttle',50000,16,2000,5,43238,'Theta-class T-2c shuttle',1000000,'Cygnus Spaceworks','theta-class_t-2c_shuttle.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (61,NULL,'Emergency Firespeeder',NULL,NULL,NULL,2,NULL,'Fire suppression speeder',NULL,NULL,'emergency_firespeeder.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (62,'2 years','Republic attack cruiser',20000000,2000,975,7400,1137,'Senator-class Star Destroyer',59000000,'Kuat Drive Yards, Allanteen Six shipyards','republic_attack_cruiser.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (63,NULL,'Naboo star skiff',NULL,3,1050,3,47150,'J-type star skiff',NULL,'Theed Palace Space Vessel Engineering Corps/Nubia Star Drives, Incorporated','naboo_star_skiff.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (64,'2 days','Jedi Interceptor',60,0,1500,1,5.47,'Eta-2 Actis-class light interceptor',320000,'Kuat Systems Engineering','jedi_interceptor.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (65,'5 days','arc-170',110,0,1000,3,43234,'Aggressive Reconnaissance-170 starfighte',155000,'Incom Corporation, Subpro Corporation','arc-170.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (66,NULL,'Droid tri-fighter',0,0,1180,1,43224,'tri-fighter',20000,'Colla Designs, Phlac-Arphocc Automata Industries','droid_tri-fighter.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (67,'2 years','Banking clan frigte',40000000,NULL,NULL,200,825,'Munificent-class star frigate',57000000,'Hoersch-Kessel Drive, Inc, Gwori Revolutionary Industries','banking_clan_frigte.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (68,'3 days','Oevvaor jet catamaran',50,2,420,2,43115,'Oevvaor jet catamaran',12125,'Appazanna Engineering Works','oevvaor_jet_catamaran.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (69,NULL,'Raddaugh Gnasp fluttercraft',20,0,310,2,7,'Raddaugh Gnasp fluttercraft',14750,'Appazanna Engineering Works','raddaugh_gnasp_fluttercraft.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (70,'20 days','Clone turbo tank',30000,300,160,20,17989,'HAVw A6 Juggernaut',350000,'Kuat Drive Yards','clone_turbo_tank.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (71,NULL,'Corporate Alliance tank droid',NULL,4,100,0,10.96,'NR-N99 Persuader-class droid enforcer',49000,'Techno Union','corporate_alliance_tank_droid.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (72,NULL,'Droid gunship',0,0,820,0,43437,'HMP droid gunship',60000,'Baktoid Fleet Ordnance, Haor Chall Engineering','droid_gunship.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (73,'7 days','Belbullab-22 starfighter',140,0,1100,1,6.71,'Belbullab-22 starfighter',168000,'Feethan Ottraw Scalable Assemblies','belbullab-22_starfighter.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (74,'15 hours','V-wing',60,0,1050,1,43290,'Alpha-3 Nimbus-class V-wing starfighter',102500,'Kuat Systems Engineering','v-wing.jpg');
INSERT INTO transport(id,consumables,denomination,cargo_capacity,passengers,max_atmosphering_speed,crew,lengthiness,model,cost_in_credits,manufacturer,image) VALUES (75,'1 day','AT-RT',20,0,90,1,43161,'All Terrain Recon Transport',40000,'Kuat Drive Yards','at-rt.jpg');
